{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fc60224d-854d-4630-920e-a1fb922468d8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "from datetime import datetime\n",
    "import os\n",
    "\n",
    "# --- Sidebar: Configurações dos limiares e percentuais ---\n",
    "st.sidebar.header(\"Configurações de Limiar e Ajuste\")\n",
    "threshold_good = st.sidebar.slider(\"≥ Pontuação para treino normal\", 0, 10, 8)\n",
    "threshold_moderate = st.sidebar.slider(\"≥ Pontuação para –15% de ajuste\", 0, 10, 6)\n",
    "threshold_low = st.sidebar.slider(\"≥ Pontuação para –35% de ajuste\", 0, 10, 4)\n",
    "reduction_moderate = st.sidebar.number_input(\"Redução de volume/intensidade (média) %\", min_value=0, max_value=100, value=15)\n",
    "reduction_low = st.sidebar.number_input(\"Redução de volume/intensidade (baixa) %\", min_value=0, max_value=100, value=35)\n",
    "\n",
    "# --- Perguntas do questionário ---\n",
    "st.title(\"Questionário Diário de Prontidão para Treino\")\n",
    "st.write(\"Responda cada item de 0 a 2:\")\n",
    "\n",
    "questions = {\n",
    "    \"Sono (0–2)\": \"Como foi seu sono na última noite?\",\n",
    "    \"Dor Muscular (0–2)\": \"Qual seu nível de dor muscular/rigidez hoje?\",\n",
    "    \"Fadiga (0–2)\": \"Qual seu nível de cansaço/fadiga hoje?\",\n",
    "    \"Estresse (0–2)\": \"Como está seu nível de estresse hoje?\",\n",
    "    \"Motivação (0–2)\": \"Qual sua motivação para treinar hoje?\"\n",
    "}\n",
    "\n",
    "responses = {}\n",
    "for key, label in questions.items():\n",
    "    responses[key] = st.slider(label, 0, 2, 2)\n",
    "\n",
    "# --- Cálculo da pontuação e recomendação ---\n",
    "score = sum(responses.values())\n",
    "st.subheader(f\"Sua pontuação total: {score} / 10\")\n",
    "\n",
    "if score >= threshold_good:\n",
    "    recommendation = \"Treino normal (100% do volume/intensidade).\"\n",
    "elif score >= threshold_moderate:\n",
    "    recommendation = f\"Reduzir ~{reduction_moderate}% do volume ou intensidade.\"\n",
    "elif score >= threshold_low:\n",
    "    recommendation = f\"Reduzir ~{reduction_low}% do volume ou intensidade.\"\n",
    "else:\n",
    "    recommendation = \"Repouso ou atividades regenerativas recomendadas.\"\n",
    "\n",
    "st.write(\"**Recomendação para hoje:**\", recommendation)\n",
    "\n",
    "# --- Registro histórico local em CSV (tratamento de encoding) ---\n",
    "history_file = \"history_prontidao.csv\"\n",
    "record = {\"data\": datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\"), **responses, \"score\": score, \"recomendacao\": recommendation}\n",
    "\n",
    "# Ao ler, tenta utf-8 e faz fallback para latin1\n",
    "if os.path.exists(history_file):\n",
    "    try:\n",
    "        df = pd.read_csv(history_file, encoding='utf-8')\n",
    "    except UnicodeDecodeError:\n",
    "        df = pd.read_csv(history_file, encoding='latin1')\n",
    "    df = df.append(record, ignore_index=True)\n",
    "else:\n",
    "    df = pd.DataFrame([record])\n",
    "\n",
    "# Ao salvar, força utf-8\n",
    "df.to_csv(history_file, index=False, encoding='utf-8')\n",
    "\n",
    "# --- Exibição do histórico ---\n",
    "st.subheader(\"Histórico de Respostas\")\n",
    "st.dataframe(df.sort_values(\"data\", ascending=False))\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "",
   "name": ""
  },
  "language_info": {
   "name": ""
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
